[mypy]
# Garante que você está checando a tipagem baseada no Python 3.12
python_version = 3.12

# Avisa se você esquecer de tipar os argumentos ou o retorno de uma função
disallow_untyped_defs = True

# Mostra códigos de erro específicos no terminal (ajuda a ignorar regras se precisar)
show_error_codes = True

# Ignora a falta de tipagem em bibliotecas de terceiros que não têm tipos por padrão
ignore_missing_imports = True